/* ============================================
   JOB NOTIFICATION TRACKER - DATASET
   60 Realistic Indian Tech Jobs
   ============================================ */

const jobsData = [
  // Infosys
  {
    id: 1,
    title: "SDE Intern",
    company: "Infosys",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://careers.infosys.com/jobs/1",
    description: "Join India's leading IT services company as a Software Development Engineer Intern. Work on enterprise-level projects, learn from industry experts, and gain hands-on experience in software development lifecycle. Mentorship provided throughout the internship."
  },
  {
    id: 2,
    title: "Junior Backend Developer",
    company: "Infosys",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "4–6 LPA",
    applyUrl: "https://careers.infosys.com/jobs/2",
    description: "Develop and maintain backend services for global clients. Work with microservices architecture, implement RESTful APIs, and collaborate with cross-functional teams. Strong foundation in Java and database concepts required."
  },
  // TCS
  {
    id: 3,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "Java", "Communication", "Problem Solving"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "3.5–4.5 LPA",
    applyUrl: "https://www.tcs.com/careers/jobs/3",
    description: "Start your career with Asia's largest IT services provider. Comprehensive training program covering technical and soft skills. Rotational assignments across different domains to find your best fit."
  },
  {
    id: 4,
    title: "Frontend Intern",
    company: "TCS",
    location: "Hyderabad",
    mode: "Remote",
    experience: "Fresher",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://www.tcs.com/careers/jobs/4",
    description: "Build responsive user interfaces for enterprise applications. Learn modern frontend frameworks, collaborate with UX designers, and contribute to real client projects. Perfect for aspiring frontend developers."
  },
  // Wipro
  {
    id: 5,
    title: "QA Intern",
    company: "Wipro",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Java", "Test Cases"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹18k–₹28k/month Internship",
    applyUrl: "https://careers.wipro.com/jobs/5",
    description: "Learn software testing methodologies and automation tools. Write test cases, execute manual and automated tests, and ensure quality delivery. Training on Selenium and industry best practices provided."
  },
  {
    id: 6,
    title: "Python Developer (Fresher)",
    company: "Wipro",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "Flask", "PostgreSQL"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "4–5.5 LPA",
    applyUrl: "https://careers.wipro.com/jobs/6",
    description: "Develop Python-based applications and APIs. Work with Django and Flask frameworks, integrate databases, and build scalable backend solutions. Ideal for Python enthusiasts starting their career."
  },
  // Accenture
  {
    id: 7,
    title: "Data Analyst Intern",
    company: "Accenture",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Power BI"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹22k–₹32k/month Internship",
    applyUrl: "https://www.accenture.com/in-en/careers/jobs/7",
    description: "Analyze business data and create insightful reports. Learn data visualization, statistical analysis, and work with real client datasets. Gain exposure to consulting and analytics domains."
  },
  {
    id: 8,
    title: "Java Developer (0-1)",
    company: "Accenture",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "5–7 LPA",
    applyUrl: "https://www.accenture.com/in-en/careers/jobs/8",
    description: "Build enterprise Java applications for Fortune 500 clients. Work with Spring ecosystem, implement microservices, and participate in agile development. Strong Java fundamentals and OOP concepts required."
  },
  // Capgemini
  {
    id: 9,
    title: "React Developer (1-3)",
    company: "Capgemini",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript", "Node.js"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "8–12 LPA",
    applyUrl: "https://www.capgemini.com/in-en/careers/jobs/9",
    description: "Develop modern web applications using React ecosystem. Implement state management, build reusable components, and optimize application performance. Work with international teams on challenging projects."
  },
  {
    id: 10,
    title: "SDE Intern",
    company: "Capgemini",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Angular", "Git", "Agile"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://www.capgemini.com/in-en/careers/jobs/10",
    description: "Get hands-on experience in software development with mentorship from senior engineers. Contribute to real projects, learn agile methodologies, and build a strong foundation for your tech career."
  },
  // Cognizant
  {
    id: 11,
    title: "Graduate Engineer Trainee",
    company: "Cognizant",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: [".NET", "C#", "SQL Server", "Azure"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "4–5 LPA",
    applyUrl: "https://careers.cognizant.com/in-en/jobs/11",
    description: "Join Cognizant's renowned training program. Learn Microsoft technologies, cloud fundamentals, and enterprise development practices. Fast-track your career with structured learning and real project exposure."
  },
  {
    id: 12,
    title: "Frontend Intern",
    company: "Cognizant",
    location: "Kolkata",
    mode: "Remote",
    experience: "Fresher",
    skills: ["HTML5", "CSS3", "JavaScript", "Vue.js"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹18k–₹25k/month Internship",
    applyUrl: "https://careers.cognizant.com/in-en/jobs/12",
    description: "Create engaging user interfaces for healthcare and financial clients. Learn Vue.js framework, responsive design principles, and accessibility standards. Portfolio-worthy projects guaranteed."
  },
  // IBM
  {
    id: 13,
    title: "Junior Backend Developer",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "Express", "MongoDB", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–9 LPA",
    applyUrl: "https://research.ibm.com/careers/jobs/13",
    description: "Work on cutting-edge projects at IBM Research. Build scalable backend systems, implement cloud-native solutions, and contribute to open-source initiatives. Innovation-driven environment with global exposure."
  },
  {
    id: 14,
    title: "QA Intern",
    company: "IBM",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Automation Testing", "Python", "CI/CD", "Jenkins"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://research.ibm.com/careers/jobs/14",
    description: "Join IBM's quality engineering team. Learn test automation frameworks, CI/CD pipelines, and DevOps practices. Work with AI-powered testing tools and contribute to enterprise software quality."
  },
  // Oracle
  {
    id: 15,
    title: "Java Developer (0-1)",
    company: "Oracle",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Oracle DB", "PL/SQL", "Linux"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "7–10 LPA",
    applyUrl: "https://www.oracle.com/careers/jobs/15",
    description: "Develop database solutions and enterprise applications. Work with Oracle's flagship products, learn advanced SQL and PL/SQL, and gain deep database expertise. Excellent growth opportunities."
  },
  {
    id: 16,
    title: "Data Analyst Intern",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "R", "Tableau", "Statistics"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹28k–₹38k/month Internship",
    applyUrl: "https://www.oracle.com/careers/jobs/16",
    description: "Analyze complex datasets for Oracle Cloud solutions. Learn advanced analytics, data modeling, and business intelligence tools. Work with petabyte-scale data and cutting-edge analytics platforms."
  },
  // SAP
  {
    id: 17,
    title: "SDE Intern",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["ABAP", "Java", "Cloud", "HANA"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹30k–₹40k/month Internship",
    applyUrl: "https://jobs.sap.com/jobs/17",
    description: "Intern at the world's leading enterprise software company. Learn SAP technologies, cloud platforms, and business process integration. High conversion rate to full-time roles."
  },
  {
    id: 18,
    title: "React Developer (1-3)",
    company: "SAP",
    location: "Pune",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "UI5", "Fiori", "JavaScript"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "10–15 LPA",
    applyUrl: "https://jobs.sap.com/jobs/18",
    description: "Build next-generation user interfaces for SAP products. Work with SAPUI5 and Fiori design system, create responsive applications, and shape the future of enterprise UX."
  },
  // Dell
  {
    id: 19,
    title: "Graduate Engineer Trainee",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "AWS", "Linux", "Networking"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "5–7 LPA",
    applyUrl: "https://jobs.dell.com/jobs/19",
    description: "Join Dell's engineering team working on cloud infrastructure and edge computing. Learn from industry veterans, work on scalable systems, and contribute to products used by millions globally."
  },
  {
    id: 20,
    title: "Python Developer (Fresher)",
    company: "Dell",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "Kubernetes", "Git"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "4.5–6 LPA",
    applyUrl: "https://jobs.dell.com/jobs/20",
    description: "Develop automation tools and internal applications. Work with modern DevOps practices, containerization, and cloud technologies. Strong Python skills and eagerness to learn essential."
  },
  // Amazon
  {
    id: 21,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "System Design", "Algorithms", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹60k–₹80k/month Internship",
    applyUrl: "https://www.amazon.jobs/en/jobs/21",
    description: "Amazon's prestigious SDE internship program. Work on services that impact millions of customers. Mentorship from senior engineers, real ownership of features, and high conversion to full-time roles."
  },
  {
    id: 22,
    title: "Junior Backend Developer",
    company: "Amazon",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Distributed Systems", "DynamoDB", "Lambda"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "12–18 LPA",
    applyUrl: "https://www.amazon.jobs/en/jobs/22",
    description: "Build highly scalable distributed systems at Amazon scale. Work with AWS services, design fault-tolerant architectures, and solve complex technical challenges. High bar for coding and system design."
  },
  // Flipkart
  {
    id: 23,
    title: "React Developer (1-3)",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Next.js", "Redux", "Performance"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.flipkartcareers.com/jobs/23",
    description: "Build India's largest e-commerce platform. Work on high-traffic applications, optimize performance for millions of users, and innovate in the e-commerce space. Fast-paced, high-impact environment."
  },
  {
    id: 24,
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "A/B Testing", "Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/jobs/24",
    description: "Analyze e-commerce data to drive business decisions. Work with massive datasets, build dashboards, and derive actionable insights. Learn from top data scientists in the industry."
  },
  // Swiggy
  {
    id: 25,
    title: "Frontend Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "React Native", "JavaScript", "CSS"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://careers.swiggy.com/jobs/25",
    description: "Build food delivery experiences used by millions. Work on both web and mobile applications, learn React Native, and contribute to product features that impact daily lives."
  },
  {
    id: 26,
    title: "Java Developer (0-1)",
    company: "Swiggy",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Kafka", "Redis"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "8–12 LPA",
    applyUrl: "https://careers.swiggy.com/jobs/26",
    description: "Develop backend services for real-time logistics and delivery. Work with high-throughput systems, event-driven architecture, and solve challenging scale problems."
  },
  // Razorpay
  {
    id: 27,
    title: "SDE Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Go", "Node.js", "PostgreSQL", "Payments"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹40k–₹55k/month Internship",
    applyUrl: "https://razorpay.com/jobs/27",
    description: "Join India's leading fintech company. Work on payment systems, learn financial technologies, and build products that power businesses across India. High learning curve, high reward."
  },
  {
    id: 28,
    title: "React Developer (1-3)",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "GraphQL", "Design Systems"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "12–20 LPA",
    applyUrl: "https://razorpay.com/jobs/28",
    description: "Build fintech products with exceptional user experience. Work with modern frontend stack, implement complex UI patterns, and contribute to design systems. Fintech experience valuable."
  },
  // PhonePe
  {
    id: 29,
    title: "Junior Backend Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Microservices", "Cassandra", "Kubernetes"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "10–15 LPA",
    applyUrl: "https://www.phonepe.com/careers/jobs/29",
    description: "Work on India's largest UPI payment platform. Build scalable systems handling billions of transactions, learn distributed systems, and impact digital payments in India."
  },
  {
    id: 30,
    title: "QA Intern",
    company: "PhonePe",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Automation", "Java", "Appium", "API Testing"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://www.phonepe.com/careers/jobs/30",
    description: "Ensure quality of payment applications used by 400M+ users. Learn mobile automation, API testing, and security testing. Critical role in fintech ecosystem."
  },
  // Paytm
  {
    id: 31,
    title: "Graduate Engineer Trainee",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Android", "MySQL", "Spring"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "5–7 LPA",
    applyUrl: "https://paytm.com/careers/jobs/31",
    description: "Join India's digital payments pioneer. Rotational program across teams, exposure to multiple technologies, and fast-track growth opportunities. Work on products touching millions daily."
  },
  {
    id: 32,
    title: "Python Developer (Fresher)",
    company: "Paytm",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "AWS", "Data Processing"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "4.5–6.5 LPA",
    applyUrl: "https://paytm.com/careers/jobs/32",
    description: "Build data pipelines and backend services for financial products. Work with big data technologies, cloud platforms, and learn fintech domain. Strong Python fundamentals required."
  },
  // Zoho
  {
    id: 33,
    title: "SDE Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Deluge", "JavaScript", "Product Development"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://www.zoho.com/careers/jobs/33",
    description: "Work at India's most successful SaaS company. Build business applications, learn full-stack development, and experience product-focused engineering culture. Chennai headquarters."
  },
  {
    id: 34,
    title: "Frontend Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["JavaScript", "React", "CSS", "UI/UX"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹22k–₹30k/month Internship",
    applyUrl: "https://www.zoho.com/careers/jobs/34",
    description: "Create intuitive interfaces for Zoho's suite of products. Learn from experienced frontend engineers, contribute to design systems, and build portfolio-worthy projects."
  },
  // Freshworks
  {
    id: 35,
    title: "React Developer (1-3)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Ember.js", "Ruby on Rails", "Product"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.freshworks.com/careers/jobs/35",
    description: "Build customer engagement software used globally. Work with modern and legacy codebases, contribute to product roadmap, and learn SaaS business model. Fast-growing company."
  },
  {
    id: 36,
    title: "Data Analyst Intern",
    company: "Freshworks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Looker", "Product Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹30k–₹40k/month Internship",
    applyUrl: "https://www.freshworks.com/careers/jobs/36",
    description: "Analyze product usage data to drive feature decisions. Work with product managers, build dashboards, and learn SaaS metrics. Strong SQL and analytical thinking required."
  },
  // Juspay
  {
    id: 37,
    title: "Junior Backend Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Haskell", "PureScript", "Functional Programming", "Payments"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.juspay.in/careers/jobs/37",
    description: "Work with functional programming languages on payment infrastructure. Unique opportunity to learn Haskell, build high-reliability systems, and work with cutting-edge tech stack."
  },
  {
    id: 38,
    title: "QA Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "Payments Domain", "Attention to Detail"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://www.juspay.in/careers/jobs/38",
    description: "Ensure reliability of payment systems processing millions of transactions. Learn payments domain, test critical financial flows, and work in high-stakes environment."
  },
  // CRED
  {
    id: 39,
    title: "SDE Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Kotlin", "Java", "Android", "Clean Code"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹50k–₹70k/month Internship",
    applyUrl: "https://cred.club/careers/jobs/39",
    description: "Join one of India's most talked-about fintech startups. Work on premium credit card management app, learn best practices, and be part of high-performance engineering culture."
  },
  {
    id: 40,
    title: "React Developer (1-3)",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Animation", "Premium UI"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "15–25 LPA",
    applyUrl: "https://cred.club/careers/jobs/40",
    description: "Build award-winning user interfaces. Focus on animations, micro-interactions, and premium experiences. Work with top-tier design team and push boundaries of web experiences."
  },
  // Startup - Groww
  {
    id: 41,
    title: "Frontend Intern",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "React Native", "Finance", "Growth"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://groww.in/careers/jobs/41",
    description: "Build investment platforms for India's growing investor base. Work on both web and mobile, learn fintech domain, and contribute to financial inclusion mission."
  },
  {
    id: 42,
    title: "Java Developer (0-1)",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Microservices", "Finance"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "8–14 LPA",
    applyUrl: "https://groww.in/careers/jobs/42",
    description: "Develop backend systems for stock trading and mutual funds. Work with financial data, implement secure transactions, and learn investment domain. High growth startup."
  },
  // Startup - Zerodha
  {
    id: 43,
    title: "Python Developer (Fresher)",
    company: "Zerodha",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Finance"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zerodha.com/careers/jobs/43",
    description: "Work at India's largest stock broker. Build trading platforms, work with financial data at scale, and learn from a tech-first team. Minimal bureaucracy, maximum impact."
  },
  {
    id: 44,
    title: "QA Intern",
    company: "Zerodha",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Python", "Selenium", "Trading Systems"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://zerodha.com/careers/jobs/44",
    description: "Test trading platforms where reliability is critical. Learn capital markets, work with high-precision systems, and ensure seamless trading experiences for millions."
  },
  // Startup - Meesho
  {
    id: 45,
    title: "SDE Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Kotlin", "Android", "E-commerce"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://www.meesho.io/careers/jobs/45",
    description: "Build for India's largest social commerce platform. Work on seller tools, logistics tech, and enable millions of entrepreneurs. High ownership, high impact environment."
  },
  {
    id: 46,
    title: "Data Analyst Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Statistics", "E-commerce"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹30k–₹40k/month Internship",
    applyUrl: "https://www.meesho.io/careers/jobs/46",
    description: "Analyze data for India's fastest growing e-commerce platform. Work with supply chain, pricing, and growth analytics. Learn from top-tier data team."
  },
  // Startup - Unacademy
  {
    id: 47,
    title: "React Developer (1-3)",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Video Streaming", "EdTech", "Performance"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "12–20 LPA",
    applyUrl: "https://unacademy.com/careers/jobs/47",
    description: "Build India's largest learning platform. Work on video streaming, live classes, and interactive learning experiences. EdTech experience valuable but not required."
  },
  {
    id: 48,
    title: "Junior Backend Developer",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Go", "Node.js", "MongoDB", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "8–14 LPA",
    applyUrl: "https://unacademy.com/careers/jobs/48",
    description: "Develop backend services for live learning at scale. Handle millions of concurrent users, build real-time systems, and impact education in India."
  },
  // Startup - Dream11
  {
    id: 49,
    title: "Java Developer (0-1)",
    company: "Dream11",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Kafka", "Gaming"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.dream11.com/careers/jobs/49",
    description: "Build India's biggest fantasy sports platform. Work on high-traffic systems during IPL and World Cup, handle millions of concurrent users, and learn gaming tech."
  },
  {
    id: 50,
    title: "Frontend Intern",
    company: "Dream11",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Animation", "Gaming UI", "Performance"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://www.dream11.com/careers/jobs/50",
    description: "Create engaging gaming experiences. Work on animations, real-time updates, and high-performance UIs. Sports enthusiast preferred but not required."
  },
  // Startup - MPL
  {
    id: 51,
    title: "Graduate Engineer Trainee",
    company: "MPL",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Android", "Gaming", "Real-time"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.mpl.live/careers/jobs/51",
    description: "Join India's leading mobile gaming platform. Build real-time multiplayer games, work on gaming infrastructure, and be part of the gaming revolution."
  },
  {
    id: 52,
    title: "Python Developer (Fresher)",
    company: "MPL",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "Data Engineering", "Analytics"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "5–8 LPA",
    applyUrl: "https://www.mpl.live/careers/jobs/52",
    description: "Build data pipelines and analytics for gaming platform. Work with user behavior data, implement ML models, and drive data-informed decisions."
  },
  // Startup - ShareChat
  {
    id: 53,
    title: "SDE Intern",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Kotlin", "Android", "Social Media"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://we.sharechat.com/careers/jobs/53",
    description: "Build for India's largest regional social media platform. Work on content creation tools, recommendation systems, and impact millions of users in tier 2/3 cities."
  },
  {
    id: 54,
    title: "Data Analyst Intern",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Recommendation Systems", "Content"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "₹30k–₹40k/month Internship",
    applyUrl: "https://we.sharechat.com/careers/jobs/54",
    description: "Analyze content and user behavior for India's vernacular social platform. Work on recommendation algorithms, content moderation, and creator analytics."
  },
  // Startup - Urban Company
  {
    id: 55,
    title: "React Developer (1-3)",
    company: "Urban Company",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "React Native", "Services", "Maps"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "12–18 LPA",
    applyUrl: "https://www.urbancompany.com/careers/jobs/55",
    description: "Build India's largest home services marketplace. Work on service provider apps, customer experience, and logistics. Real-world impact on service professionals."
  },
  {
    id: 56,
    title: "QA Intern",
    company: "Urban Company",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "Mobile Testing", "Services", "Quality"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://www.urbancompany.com/careers/jobs/56",
    description: "Ensure quality of services marketplace app. Test booking flows, service provider features, and payment systems. Work on product that impacts millions of households."
  },
  // Startup - Ola
  {
    id: 57,
    title: "Junior Backend Developer",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Kafka", "Geolocation"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.olacabs.com/careers/jobs/57",
    description: "Build ride-hailing technology used by millions. Work on real-time tracking, pricing algorithms, and driver-partner features. High-scale, high-impact systems."
  },
  {
    id: 58,
    title: "Frontend Intern",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Maps", "Real-time", "Mobile Web"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹28k–₹40k/month Internship",
    applyUrl: "https://www.olacabs.com/careers/jobs/58",
    description: "Create seamless booking experiences. Work on maps integration, real-time tracking UIs, and optimize for low-bandwidth conditions. Impact daily commute for millions."
  },
  // Startup - Zomato
  {
    id: 59,
    title: "Java Developer (0-1)",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Microservices", "Food Tech", "High Scale"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.zomato.com/careers/jobs/59",
    description: "Build food delivery technology at scale. Work on restaurant systems, delivery logistics, and customer experience. Fast-paced environment with high ownership."
  },
  {
    id: 60,
    title: "Data Analyst Intern",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Food Analytics", "Growth"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://www.zomato.com/careers/jobs/60",
    description: "Analyze food delivery data to improve customer experience. Work on restaurant recommendations, delivery time predictions, and growth analytics. Iconic food tech company."
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = jobsData;
}
